### ISSUE TITLE
Cannot convert access token to JSON.

### ISSUE THREAD

**Issue by kyeljmd** [carnellj/spmia-chapter7#4]
I was using a modified version of your authentication-service, and organization service on the branch JWT_EXAMPLE. What I've changed was the signing-key only, Whenever I request an access token on the Authorization server. I receive this response.

`{
  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb25JZCI6InNjb3JwaW9uIiwidXNlcl9uYW1lIjoiYWRtaW4iLCJzY29wZSI6WyJ3ZWJjbGllbnQiXSwiZXhwIjoxNDkxNzg1MTE2LCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6ImExOWZjZmY2LWE2MzctNDExZi04MGYzLWUyOTZhNzJlYWZmYSIsImNsaWVudF9pZCI6Im15YXBwY2xpZW50In0.FjqKMt6rtZnfydEkt4FL7ljcCu4zefj2Z6SUhM0-E6g",
  "token_type": "bearer",
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb25JZCI6InNjb3JwaW9uIiwidXNlcl9uYW1lIjoiYWRtaW4iLCJzY29wZSI6WyJ3ZWJjbGllbnQiXSwiYXRpIjoiYTE5ZmNmZjYtYTYzNy00MTFmLTgwZjMtZTI5NmE3MmVhZmZhIiwiZXhwIjoxNDk0MzMzOTE2LCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6IjMwZTFkYTc4LWIwNjYtNDhhZi1hMDFhLTMxNDQ5MTY4OTkzZSIsImNsaWVudF9pZCI6Im15YXBwY2xpZW50In0.IoFk3pGe8MvsREBt2yrzJkQYyEbzxNztHYyleExjofM",
  "expires_in": 43199,
  "scope": "webclient",
  "organizationId": "scorpion",
  "jti": "a19fcff6-a637-411f-80f3-e296a72eaffa"
}`

What i then do is access the organization resource as follows.
`curl -i -H "Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb25JZCI6InNjb3JwaW9uIiwidXNlcl9uYW1lIjoiYWRtaW4iLCJzY29wZSI6WyJ3ZWJjbGllbnQiXSwiZXhwIjoxNDkxNzg1MTE2LCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6ImExOWZjZmY2LWE2MzctNDExZi04MGYzLWUyOTZhNzJlYWZmYSIsImNsaWVudF9pZCI6Im15YXBwY2xpZW50In0.FjqKMt6rtZnfydEkt4FL7ljcCu4zefj2Z6SUhM0-E6g" -X GET http://localhost:8085/api/organization`

It then gives me this response.

`{
  "error": "invalid_token",
  "error_description": "Cannot convert access token to JSON"
}`

Is there any configuration that's needed?

**Comment by carnellj** [comment]
Hi Kyle did you check that the signing key is the same across all services.  I just double checked this branch the other day so I know this code work.


    John

**Comment by carnellj** [comment]
Hi Kyle,  

You also might want to pull the latest branch.    I upgraded everything to Camden. Sr5 about a month ago.

I know the Configurer class thing you identified was just fix last week because it was caught by the technical proofer.

    Thanks,
        John

**Comment by mysonhushu** [comment]
I find the same issue. you can refer this https://github.com/spring-projects/spring-security-oauth/issues/1788
