### ISSUE TITLE
There is more than one bean of 'OAuth2ClientContext' type

### ISSUE THREAD

**Issue by zhenyanghua** [carnellj/spmia-chapter7#8]
My IDE keeps prompting this error, how to resolve it?

![screen shot 2017-09-06 at 10 47 56 am](https://user-images.githubusercontent.com/6165894/30118428-089f818c-92f1-11e7-9004-c9efd68444d5.png)

**Comment by carnellj** [comment]
Hi Zhenyang,

Sorry I did not get back to you sooner as I have been tied up.  I have not
see this error before, but I have been using Intellij not eclipse.  I'll
dig into it in the next couple of days and see if I can resolve it.
Usually when you run into this error, the Spring Framework has found 2 bean
definitions for the same type and can not resolve it. Usually, once you
find the conflict you have to mark as primary the bean definition that you
want to use.

     Thanks,
          John

**Comment by zhenyanghua** [comment]
Hi John, 

This error goes away after switching to the feature branch so I closed it but it remains in the master branch. 

Thanks for the tip. 

Zhenyang

**Comment by pedrumJSAS** [comment]
Just to confirm I am having the same issue.  I'm having the issue on intellij. I've followed the tutorial below:

https://spring.io/guides/tutorials/spring-boot-oauth2/

**Comment by starrybleu** [comment]
Same here. Is it resolved?
![image](https://user-images.githubusercontent.com/14271094/35027089-fa6be89e-fb91-11e7-8d4b-f853dab99505.png)

**Comment by manoj7shekhawat** [comment]
You can use @Qualifier to resolve this.
`@Qualifier("oAuth2ClientContext")`
